# Generated by Django 5.1 on 2024-08-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_subject", models.CharField(max_length=50)),
                ("course_code", models.IntegerField()),
            ],
        ),
    ]
