# Generated by Django 5.1 on 2024-08-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="course_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="course_subject",
            new_name="subject",
        ),
        migrations.AddField(
            model_name="course",
            name="antireqs",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="course",
            name="coreqs",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="course",
            name="prereqs",
            field=models.CharField(default="", max_length=256),
        ),
    ]
