# Generated by Django 5.1 on 2024-08-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_course_code_course_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("study_term", models.CharField(max_length=4)),
                ("courses", models.JSONField()),
            ],
        ),
    ]
