# Generated by Django 5.1 on 2024-08-24 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_term_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="term",
            name="number",
        ),
    ]
