# Generated by Django 5.1 on 2024-09-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_term_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='antireqs',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='course',
            name='coreqs',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='term',
            name='courses',
            field=models.JSONField(default=[]),
        ),
    ]
