# Generated by Django 5.1 on 2024-09-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_course_antireqs_alter_course_coreqs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='antireqs',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='coreqs',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='term',
            name='courses',
            field=models.JSONField(),
        ),
    ]
