# Generated by Django 5.1 on 2024-09-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userterms_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userterms',
            name='terms',
            field=models.JSONField(default=list),
        ),
    ]
