# Generated by Django 5.0.7 on 2024-08-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64)),
                ("password", models.CharField(max_length=256)),
                ("email", models.CharField(max_length=256)),
                ("date_created", models.DateTimeField(blank=True)),
                ("graduation_year", models.IntegerField()),
            ],
        ),
    ]
